# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogcfg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 295)
        self.lbConfirm = QtWidgets.QPushButton(Dialog)
        self.lbConfirm.setGeometry(QtCore.QRect(470, 80, 75, 23))
        self.lbConfirm.setObjectName("lbConfirm")
        self.lbClose = QtWidgets.QPushButton(Dialog)
        self.lbClose.setGeometry(QtCore.QRect(560, 80, 75, 23))
        self.lbClose.setObjectName("lbClose")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label.setObjectName("label")
        self.txtReadStyle = QtWidgets.QTextEdit(Dialog)
        self.txtReadStyle.setGeometry(QtCore.QRect(60, 4, 571, 61))
        self.txtReadStyle.setObjectName("txtReadStyle")
        self.txtList = QtWidgets.QTextBrowser(Dialog)
        self.txtList.setGeometry(QtCore.QRect(10, 110, 621, 171))
        self.txtList.setObjectName("txtList")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbConfirm.setText(_translate("Dialog", "Confirm"))
        self.lbClose.setText(_translate("Dialog", "Close"))
        self.label.setText(_translate("Dialog", "Read UI"))
        self.txtList.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">background-color: rgb(233, 250, 255);color: rgb(85, 85, 85);font-family: Microsoft YaHei;font-size: 15px; letter-spacing: 0.2em;line-height:150%;</p></body></html>"))
