# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogshowmd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 283)
        self.txtMarkdown = QtWidgets.QTextBrowser(Dialog)
        self.txtMarkdown.setGeometry(QtCore.QRect(0, 0, 641, 251))
        self.txtMarkdown.setReadOnly(False)
        self.txtMarkdown.setObjectName("txtMarkdown")
        self.lbClosen = QtWidgets.QPushButton(Dialog)
        self.lbClosen.setGeometry(QtCore.QRect(550, 258, 75, 20))
        self.lbClosen.setObjectName("lbClosen")
        self.lbSave = QtWidgets.QPushButton(Dialog)
        self.lbSave.setGeometry(QtCore.QRect(460, 258, 75, 20))
        self.lbSave.setObjectName("lbSave")
        self.lbDelete = QtWidgets.QPushButton(Dialog)
        self.lbDelete.setGeometry(QtCore.QRect(10, 258, 75, 20))
        self.lbDelete.setObjectName("lbDelete")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbClosen.setText(_translate("Dialog", "Close(ESC"))
        self.lbSave.setText(_translate("Dialog", "Save(F12)"))
        self.lbDelete.setText(_translate("Dialog", "Delete"))
