# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogmarkdown.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 265)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 230, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.txtMark = QtWidgets.QTextEdit(Dialog)
        self.txtMark.setGeometry(QtCore.QRect(10, 30, 621, 191))
        self.txtMark.setObjectName("txtMark")
        self.lbTitle = QtWidgets.QLabel(Dialog)
        self.lbTitle.setGeometry(QtCore.QRect(10, 10, 621, 16))
        self.lbTitle.setObjectName("lbTitle")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbTitle.setText(_translate("Dialog", "TextLabel"))
